spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/jpsimmo
        username: postgres
        password: sojez

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update



    


    
